# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-14 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170502_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserXmpp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmpp', models.EmailField(max_length=254, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User XMPP address',
                'verbose_name_plural': 'User XMPP addresses',
            },
        ),
    ]
