# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-14 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userxmpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorynotification',
            name='xmpp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserXmpp'),
        ),
        migrations.AlterUniqueTogether(
            name='categorynotification',
            unique_together=set([('user', 'xmpp', 'device', 'category', 'verified')]),
        ),
    ]
